apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bankofanthos
spec:
  ingressClassName: nginx # use only with k8s version >= 1.18.0
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
