version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:nginxinc/kic-reference-architectures.git
analyze:
  modules:
  - name: pulumi/python
    type: pip
    path: pulumi/python
    target: pulumi/python
    options:
      strategy: pip
      requirements: config/pulumi/requirements.txt
