version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: kic-reference-architectures
analyze:
  modules:
  - name: github.com/nginxinc/kic-reference-architectures/pulumi/aws
    type: pip
    path: pulumi/aws
    target: pulumi/aws
    options:
      strategy: pip
      requirements: pulumi/aws/requirements.txt
