version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:nginxinc/kic-reference-architectures.git
analyze:
  modules:
  - name: pulumi/aws
    type: pip
    path: pulumi/aws
    target: pulumi/aws
    options:
      strategy: pip
      requirements: pulumi/aws/requirements.txt
