# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-ast

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
    -   id: autopep8

-   repo: https://github.com/asottile/dead
    rev: v1.5.0
    hooks:
    -   id: dead

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -  id: shellcheck
    -  id: shfmt
    -  id: markdownlint

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -  id: flake8

-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.11.0
    hooks:
    -  id: gitleaks

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
    -  id: detect-secrets
