ARG ARCH=amd64

FROM $ARCH/docker:latest AS docker

FROM $ARCH/centos:8
ARG UID
ARG GID
ARG DOCKER_GID=996
COPY --from=docker /usr/local/bin/docker /usr/local/bin/docker

RUN set -eux; \
    groupadd --gid $DOCKER_GID docker; \
    groupadd --gid $GID runner; \
    mkdir -p /pulumi/projects; \
    useradd --home-dir /pulumi/projects/kic-reference-architectures \
        --groups docker --uid $UID --gid $GID --shell /bin/bash --create-home runner

COPY --chown=runner:runner . /pulumi/projects/kic-reference-architectures

RUN set -eux; \
    yum install --quiet -y \
        gcc \
        bzip2-devel \
        libffi-devel \
        readline-devel \
        sqlite-devel \
        openssl-devel \
        zlib-devel \
        make \
        git \
        vim \
        nano; \
    su --group runner runner --login --command '/pulumi/projects/kic-reference-architectures/setup_venv.sh'; \
    echo 'source /pulumi/projects/kic-reference-architectures/venv/bin/activate' >> /pulumi/projects/kic-reference-architectures/.bashrc; \
    yum remove --quiet -y \
        gcc \
        bzip2-devel \
        libffi-devel \
        readline-devel \
        sqlite-devel \
        openssl-devel \
        zlib-devel; \
    yum clean all; \
    rm -rf /var/cache/yum /var/tmp/* /tmp/* /usr/share/man/* /root/.cache \
        /pulumi/projects/kic-reference-architectures/.cache \
        /pulumi/projects/kic-reference-architectures/venv/bin/pulumi-language-dotnet \
        /pulumi/projects/kic-reference-architectures/venv/bin/pulumi-language-go \
        /pulumi/projects/kic-reference-architectures/venv/bin/pulumi-language-nodejs; \
    find -type d -name __pycache__ -exec rm --force --recursive  '{}' \; 2> /dev/null || true

USER runner
WORKDIR /pulumi/projects/kic-reference-architectures

CMD ["/bin/bash", "--login"]
