---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: accounts-db
  labels:
    app: accounts-db
    tier: db
spec:
  serviceName: "accounts-db"
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
      tier: db
  template:
    metadata:
      labels:
        app: accounts-db
        tier: db
    spec:
      serviceAccountName: default
      containers:
      - name: accounts-db
        image: gcr.io/bank-of-anthos/accounts-db:v0.4.3
        envFrom:
          - configMapRef:
              name: environment-config
          - configMapRef:
              name: accounts-db-config
          - configMapRef:
              name: demo-data-config
        ports:
          - containerPort: 5432
            name: postgredb
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgresdb
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
  labels:
    app: accounts-db
    tier: db
spec:
  ports:
    - port: 5432
      name: tcp
      targetPort: 5432
      protocol: TCP
  selector:
    app: accounts-db
    tier: db
